In [5]:
import numpy as np

- Max number of trades: 5
- You must begin your first trade and end your last trade with our own currency; SeaShells

In [6]:
prod_dict = {
    0: 'Snowballs',
    1: 'Pizzas',
    2: 'Silicon Nuggets',
    3: 'Sea Shells'
}

In [7]:
conv = np.array([
[1, 1.45, 0.52, 0.72],
[0.7, 1, 0.31, 0.48],
[1.95, 3.1, 1, 1.49],
[1.34, 1.98, 0.64, 1]
])
print(conv)

[[1.   1.45 0.52 0.72]
 [0.7  1.   0.31 0.48]
 [1.95 3.1  1.   1.49]
 [1.34 1.98 0.64 1.  ]]


In [8]:
pnls = {}
for p1 in range(4):
    prod = conv[3, p1] * conv[p1, 3]
    pnls[p1] = prod

max_pnl = max(pnls.values())
print(max_pnl)
best_convs = [k for k in pnls.keys() if pnls[k] == max_pnl][0]
print(best_convs)

1.0
3


In [9]:
pnls = {}
for p1 in range(4):
    for p2 in range(4):
        prod = conv[3, p1] * conv[p1, p2] * conv[p2, 3]
        pnls[(p1, p2)] = prod

max_pnl = max(pnls.values())
print(max_pnl)
best_convs = [k for k in pnls.keys() if pnls[k] == max_pnl][0]
print(best_convs)

1.038232
(0, 2)


In [10]:
pnls = {}
for p1 in range(4):
    for p2 in range(4):
        for p3 in range(4):
            prod = conv[3, p1] * conv[p1, p2] * conv[p2, p3] * conv[p3, 3]
            pnls[(p1, p2, p3,)] = prod

max_pnl = max(pnls.values())
print(max_pnl)
best_convs = [k for k in pnls.keys() if pnls[k] == max_pnl][0]
print(best_convs)

1.0738728
(1, 0, 2)


In [11]:
pnls = {}
for p1 in range(4):
    for p2 in range(4):
        for p3 in range(4):
            for p4 in range(4):
                prod = conv[3, p1] * conv[p1, p2] * conv[p2, p3] * conv[p3, p4] * conv[p4, 3]
                pnls[(p1, p2, p3, p4)] = prod

max_pnl = max(pnls.values())
print(max_pnl)
best_convs = [k for k in pnls.keys() if pnls[k] == max_pnl][0]
print(best_convs)

1.08868032
(0, 2, 1, 0)


In [12]:
print('Optimal conversions:\n')
print(f'{prod_dict[3]} --> {prod_dict[best_convs[0]]}')
print(f'{prod_dict[best_convs[0]]} --> {prod_dict[best_convs[1]]}')
print(f'{prod_dict[best_convs[1]]} --> {prod_dict[best_convs[2]]}')
print(f'{prod_dict[best_convs[2]]} --> {prod_dict[best_convs[3]]}')
print(f'{prod_dict[best_convs[3]]} --> {prod_dict[3]}')

Optimal conversions:

Sea Shells --> Snowballs
Snowballs --> Silicon Nuggets
Silicon Nuggets --> Pizzas
Pizzas --> Snowballs
Snowballs --> Sea Shells


In [13]:
print(f'Highest PnL: {int(np.round(500_000 * (max_pnl - 1)))}')

Highest PnL: 44340
